name: Build and publish image

on:
  push:
    branches: main
  workflow_dispatch:

env:
  IMAGE_NAME: build-container
  GHCR_PREFIX: ghcr.io/${{ github.repository_owner }}

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix env
        run: |
          echo "GHCR_PREFIX=$(echo $GHCR_PREFIX | tr [A-Z] [a-z])" | tee -a $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build (and publish) image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          tags: ${{ env.GHCR_PREFIX }}/${{ env.IMAGE_NAME }}:latest
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
