name: Build and publish image

on:
  push:
    branches: main
  workflow_dispatch:

env:
  IMAGE_NAME: build-container
  DEFAULT_TAG: ghcr.io/${{ github.repository_owner }}/${{ IMAGE_NAME }}

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build (and publish) image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Containerfile
          tags: ${{ env.DEFAULT_TAG }}:latest
          publish: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
